### ISSUE TITLE
feature request: ask the bot who else is connected

### ISSUE THREAD

**Issue by asdfsag** [Thynix/RelayBot#3]
would be a nice feature, like ``!names`` and if the bot is reading that somewhere (even if not in the beginning of the line but at the end or in the middle so it can be used through other RelayBot's) it would output the output of ``/names`` to the channel it is asked from of the channel it is relaying to/from.

Thanks a lot in advance

**Comment by Thynix** [comment]
Hi,

I don't maintain this repo any more - see https://github.com/str4d/RelayBot for a more recently-updated fork.
